services:
  toyzzshop-watcher:
    build:
      context: .
      network: host
    image: toyzzshop-watcher:latest
    container_name: toyzzshop-watcher
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      CHECK_INTERVAL_SECONDS: "60"
    volumes:
      - ./data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
