services:
  armaganoyuncak-watcher:
    build:
      context: .
      network: host
    image: armaganoyuncak-watcher:latest
    container_name: armaganoyuncak-watcher
    restart: unless-stopped
    network_mode: host
    cpus: 0.5
    env_file:
      - .env
    environment:
      CHECK_INTERVAL_SECONDS: "60"
    volumes:
      - ./data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
